.PHONY: clean All

All:
	@echo "----------Building project:[ flipflop_irq_erik - Debug ]----------"
	@cd "flipflop_irq_erik" && "$(MAKE)" -f  "flipflop_irq_erik.mk" && "$(MAKE)" -f  "flipflop_irq_erik.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ flipflop_irq_erik - Debug ]----------"
	@cd "flipflop_irq_erik" && "$(MAKE)" -f  "flipflop_irq_erik.mk" clean
