.PHONY: clean All

All:
	@echo "----------Building project:[ sysick_irq - Debug ]----------"
	@cd "sysick_irq" && "$(MAKE)" -f  "sysick_irq.mk" && "$(MAKE)" -f  "sysick_irq.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ sysick_irq - Debug ]----------"
	@cd "sysick_irq" && "$(MAKE)" -f  "sysick_irq.mk" clean
