.PHONY: clean All

All:
	@echo "----------Building project:[ GPIO - Release ]----------"
	@cd "GPIO" && "$(MAKE)" -f  "GPIO.mk" && "$(MAKE)" -f  "GPIO.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ GPIO - Release ]----------"
	@cd "GPIO" && "$(MAKE)" -f  "GPIO.mk" clean
