.PHONY: clean All

All:
	@echo "----------Building project:[ delay - Debug ]----------"
	@cd "delay" && "$(MAKE)" -f  "delay.mk" && "$(MAKE)" -f  "delay.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ delay - Debug ]----------"
	@cd "delay" && "$(MAKE)" -f  "delay.mk" clean
